"""
Explanation Service – Module 6 Technology Intelligence

Generates structured, evidence-based explanations for technology
maturity classifications.

Rules:
- Explanations are derived from calculated indicators
- NOT generated by LLM (LLM may later format, but indicators are the source of truth)
- The explanation object contains: summary, evidence list, limitations list
"""
from __future__ import annotations


def build_explanation(
    stage: str,
    research_direction: str | None,
    patent_direction: str | None,
    org_direction: str | None,
    app_direction: str | None,
    adoption_level: str | None,
    adoption_trend: str | None,
    years_analysed: int | None,
    research_growth: float | None,
    patent_growth: float | None,
    org_values: list[int | None] | None = None,
    app_values: list[int | None] | None = None,
    data_coverage: dict | None = None,
) -> dict:
    """
    Build the structured explanation object.

    Returns:
        {
            "summary": str,
            "evidence": [str, ...],
            "limitations": [str, ...]
        }
    """
    evidence: list[str] = []
    limitations: list[str] = []

    n = years_analysed or 0

    # ── Evidence from research ───────────────────────────────────────────────
    if research_direction == "Increasing":
        rg_str = f" ({research_growth:+.1f}% avg YoY)" if research_growth is not None else ""
        evidence.append(f"Research activity increased over {n} years{rg_str}")
    elif research_direction == "Decreasing":
        evidence.append(f"Research activity declined over {n} years")
    elif research_direction == "Stable":
        evidence.append(f"Research activity was relatively stable over {n} years")
    elif research_direction == "Insufficient Data":
        limitations.append("Insufficient research data years for reliable trend analysis (need ≥ 3 years)")

    # ── Evidence from patents ────────────────────────────────────────────────
    if patent_direction == "Increasing":
        pg_str = f" ({patent_growth:+.1f}% avg YoY)" if patent_growth is not None else ""
        evidence.append(f"Patent activity increased over {n} years{pg_str}")
    elif patent_direction == "Decreasing":
        evidence.append(f"Patent activity declined over {n} years")
    elif patent_direction == "Stable":
        evidence.append("Patent activity was relatively stable")
    elif patent_direction == "Insufficient Data":
        limitations.append("Insufficient patent data for reliable trend analysis")

    # ── Evidence from organizations ──────────────────────────────────────────
    if org_direction == "Increasing":
        evidence.append("Organization participation is increasing")
    elif org_direction == "Decreasing":
        evidence.append("Organization participation has decreased")
    elif org_direction == "Stable":
        evidence.append("Organization participation is stable")

    # ── Evidence from applications ───────────────────────────────────────────
    if app_direction == "Increasing":
        evidence.append("Application and use-case diversity is expanding")
    elif app_direction == "Decreasing":
        evidence.append("Application diversity has narrowed")

    # ── Adoption signal ──────────────────────────────────────────────────────
    if adoption_level:
        evidence.append(f"Adoption level: {adoption_level}")
        if adoption_trend and adoption_trend != "Insufficient Data":
            evidence.append(f"Adoption trend: {adoption_trend}")

    # ── Limitations ─────────────────────────────────────────────────────────
    if n < 3:
        limitations.append(f"Only {n} year(s) of data available; trend reliability is limited")

    if data_coverage:
        adoption_years = data_coverage.get("adoptionYears", 0)
        if adoption_years < 3:
            limitations.append(f"Adoption data available for only {adoption_years} year(s)")

    # ── Generate summary ─────────────────────────────────────────────────────
    summary = _build_summary(
        stage, research_direction, patent_direction, adoption_level, adoption_trend
    )

    return {
        "summary": summary,
        "evidence": evidence,
        "limitations": limitations,
    }


def _build_summary(
    stage: str,
    research_direction: str | None,
    patent_direction: str | None,
    adoption_level: str | None,
    adoption_trend: str | None,
) -> str:
    """Generate a plain-language summary sentence."""
    r_up = research_direction == "Increasing"
    r_down = research_direction == "Decreasing"
    p_up = patent_direction == "Increasing"
    p_down = patent_direction == "Decreasing"

    if stage == "Emerging":
        return (
            "Research and patent activity are beginning to emerge. "
            "Organization participation is early-stage and adoption is limited."
        )

    if stage == "Developing":
        parts = []
        if r_up and p_up:
            parts.append("Research and patent activity show strong multi-year growth")
        elif r_up:
            parts.append("Research activity shows strong multi-year growth")
        elif p_up:
            parts.append("Patent activity shows strong multi-year growth")

        if adoption_level in ("Low", None, "Insufficient Data"):
            parts.append("while adoption remains relatively low")
        elif adoption_level == "Medium":
            parts.append("with moderate adoption beginning")

        return (", ".join(parts) + ".").capitalize() if parts else (
            "The technology is in an active development phase with growing research and patent interest."
        )

    if stage == "Mature":
        adoption_str = ""
        if adoption_level == "High":
            adoption_str = " and adoption is high"
        elif adoption_level == "Medium":
            adoption_str = " with moderate adoption"
        return (
            f"The technology has high accumulated research and patent activity"
            f"{adoption_str}. "
            "Growth has stabilised, indicating a mature technology ecosystem."
        )

    if stage == "Declining":
        return (
            "Research and patent activity have decreased across the analysed period, "
            "indicating declining technology activity."
        )

    return "Classification based on available multi-year research and patent data."
